### ISSUE TITLE
installable app support

### ISSUE THREAD

**Issue by maxence-charriere** [lu4p/astextract#4]
Hey, I'm the creator of [go-app](https://github.com/maxence-charriere/go-app).

I was thinking that it would be cool to have this available as an installable app. I updated the package version to v7.0.3 and it makes it possible with GitHub Pages hosted apps.

You would just have to update go-app and push it to your repo.

Also, since your app is white, you may want to tweak the handler by specifying a white theme color:

```go
app.Handler{
    // ...
    ThemeColor: "#ffffff",
}
```

Best,
Maxence

**Comment by maxence-charriere** [comment]
You may also want to put your own logo since the default one will be go-app logo.

```go
app.Handler{
    ThemeColor: "#ffffff",
    Icon: app.Icon{
          Default: "/web/YOUR_ICON.png",
    },
}
```

**Comment by lu4p** [comment]
Updated to 7.0.3.
I don't have a logo, so I will keep using the default one.
Will apply themecolor tweak.

**Comment by maxence-charriere** [comment]
Awesome.
I think you also have to re-generate your static files.

**Comment by lu4p** [comment]
@maxence-charriere Yes I just realized that

**Comment by lu4p** [comment]
I applied the suggested tweak, and also tried to set the background color, but the loading screen is still dark.

```go
	h := &app.Handler{
		Name:            "astextract",
		Title:           "astextract",
		BackgroundColor: "#ffffff",
		ThemeColor:      "#ffffff",
		Author:          "lu4p",
		Styles:          []string{"https://unpkg.com/spectre.css/dist/spectre.min.css"},
	}

```

**Comment by lu4p** [comment]
Regenerated files are now live.

**Comment by maxence-charriere** [comment]
When you install on chrome on desktop, the windows bar is taking the same color as the content.

```go
// The theme color for the application. This affects how the OS displays the
// app (e.g., PWA title bar or Android's task switcher).
//
// DEFAULT: #2d2c2c.
ThemeColor string
```

for the loading screen, you can overload the color with css:
```css
.goapp-app-info {
    color: black;
    background-color: white;
}
```

**Comment by lu4p** [comment]
Ok thanks.

**Comment by lu4p** [comment]
@maxence-charriere Set the themecolor to white now.

**Comment by lu4p** [comment]
@maxence-charriere When do you plan to put this tool into the live section?

**Comment by maxence-charriere** [comment]
it is now :)
